site_name: ThitsaWorks Platform
site_description: Mojaloop platform documentation
site_url: https://docs.thitsaworks.com
use_directory_urls: true

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/fav.png
  features:
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - navigation.instant
    - content.tabs.link
    - navigation.footer
    - header.autohide
    - navigation.expand
    - content.code.copy

extra:
  version:
    provider: mike

nav:
  - Home: index.md

  - Architecture:
      - Platform Architecture Overview: platform-architecture-overview.md

  - Security:
      - Hub â†” PM4ML: hub-pm4ml-security-architecture.md

  - Deployment:
      - Deploy Mojaloop Locally (MicroK8s): deploy-mojaloop-local-microk8s.md    
      - Deploy Mojaloop Locally (Without Kubernetes): deploy-mojaloop-local-withoutk8s.md
      - Deploy Mojaloop Payment Manager (On-Premise): deploy-payment-manager-on-premise.md
