site_name: ThitsaX Docs
site_description: Platform security & architecture documentation
site_url: https://thitsax.github.io/docs/
use_directory_urls: true

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - navigation.instant
    - content.tabs.link
    - navigation.footer
    - header.autohide
    - navigation.expand

extra:
  version:
    provider: mike

extra_files:
  - index.html
nav:
  - Home: index.md
  - Security:
      - Hub â†” PM4ML: hub-pm4ml-security-architecture.md
